# Sample data consisting of two mentions
MENTIONS = [  
    {  
    u'contributors':None,
    u'truncated':False,
    u'text':u'The CS&amp;IT lab will be open to alumni during Homecoming, Saturday 10am-Noon. See what students are doing, like @SalviusRobot',
    u'is_quote_status':False,
    u'in_reply_to_status_id':None,
    u'id':649703760697143296,
    u'favorite_count':1,
    u'source':u'<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
    u'retweeted':True,
    u'coordinates':None,
    u'entities':{  
     u'symbols':[],
     u'user_mentions':[  
        {  
           u'id':712978718,
           u'indices':[  
              114,
              127
           ],
           u'id_str':u'712978718',
           u'screen_name':u'SalviusRobot',
           u'name':u'Salvius the Robot'
        }
     ],
     u'hashtags':[],
     u'urls':[]
    },
    u'in_reply_to_screen_name':None,
    u'id_str':u'649703760697143296',
    u'retweet_count':1,
    u'in_reply_to_user_id':None,
    u'favorited':True,
    u'user':{  
     u'follow_request_sent':False,
     u'has_extended_profile':False,
     u'profile_use_background_image':True,
     u'default_profile_image':False,
     u'id':2885705333,
     u'profile_background_image_url_https':u'https://abs.twimg.com/images/themes/theme14/bg.gif',
     u'verified':False,
     u'profile_text_color':u'333333',
     u'profile_image_url_https':u'https://pbs.twimg.com/profile_images/535493614294409216/MzEZDbOR_normal.jpeg',
     u'profile_sidebar_fill_color':u'EFEFEF',
     u'entities':{  
        u'url':{  
           u'urls':[  
              {  
                 u'url':u'http://t.co/NJTahpXBlu',
                 u'indices':[  
                    0,
                    22
                 ],
                 u'expanded_url':u'http://www1.wne.edu/artsandsciences/index.cfm?selection=doc.4836',
                 u'display_url':u'www1.wne.edu/artsandscience\u2026'
              }
           ]
        },
        u'description':{  
           u'urls':[]
        }
     },
     u'followers_count':47,
     u'profile_sidebar_border_color':u'EEEEEE',
     u'id_str':u'2885705333',
     u'profile_background_color':u'131516',
     u'listed_count':0,
     u'is_translation_enabled':False,
     u'utc_offset':None,
     u'statuses_count':56,
     u'description':u'The Department of Computer Science and Information Technology at @WNEUniversity',
     u'friends_count':38,
     u'location':u'Springfield, MA',
     u'profile_link_color':u'009999',
     u'profile_image_url':u'http://pbs.twimg.com/profile_images/535493614294409216/MzEZDbOR_normal.jpeg',
     u'following':True,
     u'geo_enabled':False,
     u'profile_banner_url':u'https://pbs.twimg.com/profile_banners/2885705333/1416506808',
     u'profile_background_image_url':u'http://abs.twimg.com/images/themes/theme14/bg.gif',
     u'screen_name':u'WNECSIT',
     u'lang':u'en',
     u'profile_background_tile':True,
     u'favourites_count':1,
     u'name':u'WNE CS and IT Dept.',
     u'notifications':False,
     u'url':u'http://t.co/NJTahpXBlu',
     u'created_at':u'Thu Nov 20 15:09:36+0000 2014',
     u'contributors_enabled':False,
     u'time_zone':None,
     u'protected':False,
     u'default_profile':False,
     u'is_translator':False
    },
    u'geo':None,
    u'in_reply_to_user_id_str':None,
    u'lang':u'en',
    u'created_at':u'Thu Oct 01 21:53:42+0000 2015',
    u'in_reply_to_status_id_str':None,
    u'place':None
    },

    {  
    u'contributors':None,
    u'truncated':False,
    u'text':u"Lookin' good, @salviusrobot ! | Salvius: A Humanoid Robot Born from a Junkyard http://t.co/NYOVJVlzhW #Recycle #robots #robotech #makers",
    u'is_quote_status':False,
    u'in_reply_to_status_id':None,
    u'id':620985108204384257,
    u'favorite_count':1,
    u'source':u'<a href="https://about.twitter.com/products/tweetdeck" rel="nofollow">TweetDeck</a>',
    u'retweeted':False,
    u'coordinates':None,
    u'entities':{  
       u'symbols':[  

       ],
       u'user_mentions':[  
          {  
             u'id':712978718,
             u'indices':[  
                14,
                27
             ],
             u'id_str':u'712978718',
             u'screen_name':u'SalviusRobot',
             u'name':u'Salvius the Robot'
          }
       ],
       u'hashtags':[  
          {  
             u'indices':[  
                102,
                110
             ],
             u'text':u'Recycle'
          },
          {  
             u'indices':[  
                111,
                118
             ],
             u'text':u'robots'
          },
          {  
             u'indices':[  
                119,
                128
             ],
             u'text':u'robotech'
          },
          {  
             u'indices':[  
                129,
                136
             ],
             u'text':u'makers'
          }
       ],
       u'urls':[  
          {  
             u'url':u'http://t.co/NYOVJVlzhW',
             u'indices':[  
                79,
                101
             ],
             u'expanded_url':u'http://makezine.com/2015/07/13/salvius-humanoid-robot-born-junkyard/',
             u'display_url':u'makezine.com/2015/07/13/sal\u2026'
          }
       ]
    },
    u'in_reply_to_screen_name':None,
    u'id_str':u'620985108204384257',
    u'retweet_count':0,
    u'in_reply_to_user_id':None,
    u'favorited':False,
    u'user':{  
       u'follow_request_sent':False,
       u'has_extended_profile':False,
       u'profile_use_background_image':True,
       u'default_profile_image':False,
       u'id':1592524638,
       u'profile_background_image_url_https':u'https://abs.twimg.com/images/themes/theme1/bg.png',
       u'verified':False,
       u'profile_text_color':u'333333',
       u'profile_image_url_https':u'https://pbs.twimg.com/profile_images/606888255175270401/6lmq5ZP5_normal.png',
       u'profile_sidebar_fill_color':u'DDEEF6',
       u'entities':{  
          u'url':{  
             u'urls':[  
                {  
                   u'url':u'http://t.co/fHiRO93C8e',
                   u'indices':[  
                      0,
                      22
                   ],
                   u'expanded_url':u'http://SDMakerFaire.org',
                   u'display_url':u'SDMakerFaire.org'
                }
             ]
          },
          u'description':{  
             u'urls':[  

             ]
          }
       },
       u'followers_count':601,
       u'profile_sidebar_border_color':u'C0DEED',
       u'id_str':u'1592524638',
       u'profile_background_color':u'C0DEED',
       u'listed_count':69,
       u'is_translation_enabled':False,
       u'utc_offset':-28800,
       u'statuses_count':1305,
       u'description':u'A hands-on feast of invention, creativity, & a celebration of the Maker movement. #MakerFaire comes to #BalboaPark Oct 3+4! Tell us:what will you make?',
       u'friends_count':307,
       u'location':u'San Diego, CA',
       u'profile_link_color':u'0084B4',
       u'profile_image_url':u'http://pbs.twimg.com/profile_images/606888255175270401/6lmq5ZP5_normal.png',
       u'following':False,
       u'geo_enabled':True,
       u'profile_banner_url':u'https://pbs.twimg.com/profile_banners/1592524638/1436210641',
       u'profile_background_image_url':u'http://abs.twimg.com/images/themes/theme1/bg.png',
       u'screen_name':u'SDMakerFaire',
       u'lang':u'en',
       u'profile_background_tile':False,
       u'favourites_count':1107,
       u'name':u'SDMakerFaire',
       u'notifications':False,
       u'url':u'http://t.co/fHiRO93C8e',
       u'created_at':u'Sun Jul 14 04:45:55+0000 2013',
       u'contributors_enabled':False,
       u'time_zone':u'Pacific Time (US & Canada)',
       u'protected':False,
       u'default_profile':True,
       u'is_translator':False
    },
    u'geo':None,
    u'in_reply_to_user_id_str':None,
    u'possibly_sensitive':False,
    u'lang':u'en',
    u'created_at':u'Tue Jul 14 15:56:01+0000 2015',
    u'in_reply_to_status_id_str':None,
    u'place':None
    }
]
