# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_chatterbot', '0003_rename_in_response_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='occurrence',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
