# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-27 13:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('django_chatterbot', '0004_rename_in_response_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 12, 27, 13, 49, 25, 432209, tzinfo=utc), help_text='The date and time that this statement was created at.'),
            preserve_default=False,
        ),
    ]
