# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-15 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_chatterbot', '0007_create_phrase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='statements',
        ),
        migrations.RemoveField(
            model_name='response',
            name='occurrence',
        ),
        migrations.RemoveField(
            model_name='statement',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='statement',
            name='phrase',
        ),
        migrations.AddField(
            model_name='conversation',
            name='responses',
            field=models.ManyToManyField(help_text='The responses in this conversation.', related_name='conversations', to='django_chatterbot.Response'),
        ),
        migrations.AddField(
            model_name='response',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time that this statement was created at.'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='text',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='Phrase',
        ),
    ]
