# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-01-22 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_chatterbot', '0007_remove_root_related_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='conversation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='django_chatterbot.Conversation'),
        ),
    ]
