# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_chatterbot', '0009_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='text',
            field=models.CharField(max_length=400, unique=True),
        ),
    ]
