# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-01-22 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_chatterbot', '0009_conversation_root_null'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='root',
        ),
        migrations.RemoveField(
            model_name='statement',
            name='conversation',
        ),
        migrations.AddField(
            model_name='conversation',
            name='statements',
            field=models.ManyToManyField(help_text=b'The statements in this conversation.', null=True, related_name='conversation', to='django_chatterbot.Statement'),
        ),
    ]
