# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-01-25 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_chatterbot', '0010_conversation_statements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
