# Generated by Django 4.2.19 on 2025-02-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_chatterbot', '0018_text_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='statement',
            index=models.Index(fields=['search_text'], name='idx_cb_search_text'),
        ),
        migrations.AddIndex(
            model_name='statement',
            index=models.Index(fields=['search_in_response_to'], name='idx_cb_search_in_response_to'),
        ),
    ]
